Ogani/Models/Concretes/Tag.cs
using Ogani.Models.Abstracts;

namespace Ogani.Models.Concretes
{
    public class Tag : Entity
    {
        public string Name { get; set; }
        public IEnumerable<Product> Products { get; set; }
    }
}

Ogani/Areas/Admin/Controllers/TagsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ogani.Data;
using Ogani.Models.Concretes;
using Ogani.ViewModels;

namespace Ogani.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Moderator")]
    public class TagsController : Controller
    {
        private readonly AppDbContext _dbContext;

        public TagsController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<TagIndexViewModel> tags = new();

            foreach (var tag in _dbContext.Tags.Include("Products"))
            {
                tags.Add(new TagIndexViewModel()
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    ProductCount = tag.Products.Count()
                });
            }

            return View(tags);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(TagAddViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            _dbContext.Tags.Add(new Tag() { Name = model.Name });
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Update(int Id)
        {
            var tag = await _dbContext.Tags.FirstOrDefaultAsync(t => t.Id == Id);

            var model = new CategoryAddViewModel
            {
                Name = tag.Name
            };

            ViewBag.TagId = tag.Id;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int Id, TagAddViewModel model)
        {
            var tag = await _dbContext.Tags.FirstOrDefaultAsync(t => t.Id == Id);

            if (!ModelState.IsValid)
                return View(model);

            tag.Name = model.Name;

            _dbContext.Tags.Update(tag);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int Id)
        {
            var tag = await _dbContext.Tags.FirstOrDefaultAsync(t => t.Id == Id);

            _dbContext.Tags.Remove(tag);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Ogani/Areas/Admin/Views/Tags/Add.cshtml
@model TagAddViewModel

@{
    ViewData["Title"] = "Add Tag Page";
}

<div class="card">
    <div class="card-body">
        <div class="card-title">Add Tag</div>
        <hr>
        <form asp-area="Admin" asp-action="Add" asp-controller="Tags" method="post">
            <div class="form-group">
                <label for="input-1">Name</label>
                <input asp-for=Name type="text" class="form-control" id="input-1" placeholder="Enter Tag Name">
                <span asp-validation-for="Name" style="color: red"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-light px-5">Add</button>
            </div>
        </form>
    </div>
</div>

Ogani/Areas/Admin/Views/Tags/Index.cshtml
@model List<TagIndexViewModel>

@{
    ViewData["Title"] = "Tags Page";
}

<div class="row">
    <div class="col-12 col-lg-12">
        <div class="card">
            <div class="card-header">
                Tags
                <div class="card-action">
                    <div class="dropdown">
                        <a href="javascript:void();" class="dropdown-toggle dropdown-toggle-nocaret" data-toggle="dropdown">
                            <i class="icon-options"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" asp-controller="Tags" asp-action="Add" asp-area="Admin">Add Tag</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table align-items-center table-flush table-borderless">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Products Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in Model)
                        {
                            <tr>
                                <td>@product.Id</td>
                                <td>@product.Name</td>
                                <td>@product.ProductCount</td>
                                <td style="padding: 12px 5px 0px 5px">
                                    <form asp-action="Update" asp-controller="Tags" asp-area="Admin" asp-route-id="@product.Id" method="get">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-light px-5">Update</button>
                                        </div>
                                    </form>
                                </td>
                                <td style="padding: 12px 5px 0px 3px">
                                    <form asp-action="Delete" asp-controller="Tags" asp-area="Admin" asp-route-id="@product.Id" method="post">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-light px-5">Delete</button>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Ogani/Areas/Admin/Views/Tags/Update.cshtml
@model CategoryAddViewModel

@{
    ViewData["Title"] = "Update Tag Page";
}

<div class="card">
    <div class="card-body">
        <div class="card-title">Update Tag</div>
        <hr>
        <form asp-area="Admin" asp-action="Update" asp-controller="Tags" asp-route-id="@ViewBag.TagId" method="post">
            <div class="form-group">
                <label for="input-1">Name</label>
                <input asp-for=Name type="text" class="form-control" id="input-1" placeholder="Enter Tag Name">
                <span asp-validation-for="Name" style="color: red"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-light px-5">Update</button>
            </div>
        </form>
    </div>
</div>